/*--------------------------------------15 products or items data involved----------------------------------*/
const data = {
    products: [
        {
        name: "Nike Sportswear Phoenix Fleece",
        slug: "Women's Oversize Crew Neck Sweatshirt",
        category: "Sweatshirt",
        image: "https://i.ibb.co/nryP9sM/sportswear-phoenix-fleece-over-oversized-crew-neck-sweatshirt-g-Gz-PT0.jpg", // 679px × 829px
        price: "RM 120",
        brand: "Nike",
        // rating: 4.5,
        // numReviews: 10,
        // description: "high quality shirt",
        },
        {
        name: "Nike Sportswear",
        slug: "Men's French Terry Pullover Hoodie",
        category: "Hoodie",
        image: "https://i.ibb.co/4MgpDr3/sportswear-french-terry-pullover-hoodie-3s-Jg7-R.png",
        price: "RM 335",
        brand: "Nike",
        // rating: 4.0,
        // numReviews: 10,
        // description: "high quality product",
        },
        {
        name: "NikeCourt Dri-FIT Advantage",
        slug: "Men's Tennis Shorts",
        category: "Shorts",
        image: "https://i.ibb.co/d4smJsH/nikecourt-dri-fit-advantage-18cm-tennis-shorts-mv-LJw-R.jpg",
        price: "RM 195",
        brand: "Nike",
        // rating: 4.5,
        // numReviews: 14,
        // description: "high quality product",
        },
        {
        name: "Nike Dri-FIT DYE",
        slug: "Men's Training Track",
        category: "Pants",
        image: "https://i.ibb.co/YypLjJ1/dri-fit-dye-training-tank-d-XPMs-F.jpg",
        price: "RM 99",
        brand: "Nike",
        // rating: 4.5,
        // numReviews: 10,
        // description: "high quality product",
        },
        {
            name: "Nike Everyday Plus Lightweight",
            slug: "Women's Training No-Show Socks",
            category: "Socks",
            image: "https://i.ibb.co/2MSRK2S/everyday-plus-lightweight-training-no-show-socks-V4w0p9.jpg",
            price: "RM 69",
            brand: "Nike",
            // rating: 4.5,
            // numReviews: 10,
            // description: "high quality product",
        },
        {
            name: "Jordan Flight",
            slug: "Women's Woven Jacket",
            category: "Jackets and Gilets",
            image: "https://i.ibb.co/sbzcgMk/jordan-flight-woven-jacket-B9-Gt1-J.jpg",
            price: "RM 349",
            brand: "Nike",
            // rating: 4.5,
            // numReviews: 10,
            // description: "high quality product",
        },
        {
            name: "Nike Sportswear",
            slug: "Women's Cropped T-Shirt",
            category: "Tops & T-Shirts",
            image: "https://i.ibb.co/JvLdmxW/sportswear-cropped-t-shirt-GJ1k1-Z.jpg",
            price: "RM 119",
            brand: "Nike",
            // rating: 4.5,
            // numReviews: 10,
            // description: "high quality product",
        },
        {
            name: "Nike Dri-FIT Swoosh Air Force 1",
            slug: "Women's Medium Support Laced Sports Bra",
            category: "Sports Bras",
            image: "https://i.ibb.co/kyHzMRC/dri-fit-swoosh-air-force-1-support-laced-sports-bra-vlcgf-T.jpg",
            price: "RM 279",
            brand: "Nike",
            // rating: 4.5,
            // numReviews: 10,
            // description: "high quality product",
        },
        {
            name: "Johor Darul Ta'zim FC 2022",
            slug: "Women's Nike Football Shirt",
            category: "Jerseys and Kits",
            image: "https://i.ibb.co/ZGD2wd9/johor-darul-tazim-fc-2022-stadium-home-dri-fit-football-shirt-R0z6fw.jpg",
            price: "RM 299",
            brand: "Nike",
            // rating: 4.5,
            // numReviews: 10,
            // description: "high quality product",
        },
        {
            name: "Nike Sportswear",
            slug: "Women's T-Shirt Plus Size",
            category: "Plus Size",
            image: "https://i.ibb.co/RbK5s3M/sportswear-t-shirt-k-Q3f-XF.jpg",
            price: "RM 119",
            brand: "Nike",
            // rating: 4.5,
            // numReviews: 10,
            // description: "high quality product",
        },
        {
            name: "Nike Court Advantag",
            slug: "Women's Tennis Visor",
            category: "Caps",
            image: "https://i.ibb.co/2N8WxBx/nikecourt-advantage-tennis-visor-c6-X8-Fj.jpg",
            price: "RM 59",
            brand: "Nike",
            // rating: 4.5,
            // numReviews: 10,
            // description: "high quality product",
        },
        {
            name: "Nike Sportswear Futura 365",
            slug: "Mini Backpack",
            category: "Bag and Backpacks",
            image: "https://i.ibb.co/vqCLsQJ/sportswear-futura-365-mini-backpack-2-XXKc-C.jpg",
            price: "RM 135",
            brand: "Nike",
            // rating: 4.5,
            // numReviews: 10,
            // description: "high quality product",
        },
        {
            name: "Air Jordan 1 Zoom Air Comfort",
            slug: "Men's Shoes",
            category: "Shoes",
            image: "https://i.ibb.co/9syjH5F/air-jordan-1-zoom-air-comfort-dia-de-muertos-shoes-Ct5-Nhc.jpg",
            price: "RM 749",
            brand: "Nike",
            // rating: 4.5,
            // numReviews: 10,
            // description: "high quality product",
        },
        {
            name: "Nike Oneonta",
            slug: "Sandals",
            category: "Sandals and Slides",
            image: "https://i.ibb.co/0cp0cF1/oneonta-sandals-hb3phr.jpg",
            price: "RM 99",
            brand: "Nike",
            // rating: 4.5,
            // numReviews: 10,
            // description: "high quality product",
        },
        
    ],
};
export default data;
